name: Tests

on:
  push: ~
  pull_request: ~

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Don't run forever when stale

    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'

    name: Python ${{ matrix.python-version }}

    container:
      image: python:${{ matrix.python-version }}-slim
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends git

      - name: Install Python dependencies
        run: |
          pip install --no-cache-dir -e . && \
          pip install --no-cache-dir \
            pytest \
            pytest-cov \
            pylama \
            pytest-asyncio \
            pytest-mock \
            setuptools>=70

      - name: Run tests
        run: pytest --cov=dsmr_parser test

      - name: Run pylama
        run: pylama dsmr_parser test

      - name: Code coverage upload
        uses: codecov/codecov-action@v5
